In [38]:
import numpy as np

In [39]:
lst=[1,2,3,4,5]
print(lst,type(lst))

[1, 2, 3, 4, 5] <class 'list'>


In [40]:
a=np.array(lst)
a

array([1, 2, 3, 4, 5])

In [43]:
b=np.array([[1,2,3],
            [4,5,6]])
print(b,type(b))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


In [44]:
print(a.size)
print(b.size)

5
6


In [45]:
# tell you dimension of the array(1d,2d,3d....)
b.ndim

2

In [6]:
# shape=(row,col)
print(a.shape)
print(b.shape)

(5,)
(2, 3)


In [46]:
# access array using index
b[1,2]

np.int64(6)

In [64]:
# reshape
arr=np.array([1,2,3,4,5,6])
new_arr=arr.reshape(2,3)
print(new_arr)
# new_arr.base

[[1 2 3]
 [4 5 6]]


In [7]:
# dtype
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

b.dtype

dtype('int64')

In [8]:
b=np.array([[1,2,3,4,5],[5,0.8,9,99,0]])
print(b,b.dtype)

[[ 1.   2.   3.   4.   5. ]
 [ 5.   0.8  9.  99.   0. ]] float64


In [55]:
array=np.array([1,2,3,4],dtype='S')
print(array)
new_arr=array.astype(int)
print(new_arr)

[b'1' b'2' b'3' b'4']
[1 2 3 4]


In [9]:
b.transpose()

array([[ 1. ,  5. ],
       [ 2. ,  0.8],
       [ 3. ,  9. ],
       [ 4. , 99. ],
       [ 5. ,  0. ]])

In [56]:
# copy vs view
array=np.array([1,2,3])
x=array.copy()
y=array.view()
print(x.base,y.base)

None [1 2 3]


# np ones zeros empty

In [10]:
#np.empty
# not necessay it is zero

empt=np.empty((3,4),dtype='float')
print(empt,type(empt),empt.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] <class 'numpy.ndarray'> float64


In [11]:
# creates array with ones
first_one=np.ones(3)
sec_one=np.ones((3,6),dtype='float')
print(first_one)
print(sec_one)

[1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [12]:
np.ones((3,6),dtype='str')

array([['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1']], dtype='<U1')

In [13]:
string=np.zeros((3,6),dtype='str')
string
# string.dtype

array([['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', '']], dtype='<U1')

In [14]:
booles=np.ones((3,6),dtype='bool')
booles
# booles.dtype

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

# np-arange (like loop), np.reshape,ravel,flatten

In [15]:
a=np.arange(5,23,2)
print(a,type(a))

[ 5  7  9 11 13 15 17 19 21] <class 'numpy.ndarray'>


In [16]:
b=a.reshape((3,3))
b

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [17]:
c=b.flatten()
print(b)
print(c)

[[ 5  7  9]
 [11 13 15]
 [17 19 21]]
[ 5  7  9 11 13 15 17 19 21]


In [18]:
d=b.ravel()
print(b)
print(d)

[[ 5  7  9]
 [11 13 15]
 [17 19 21]]
[ 5  7  9 11 13 15 17 19 21]



# slicing operation

In [19]:
# [start:end:step], also work for negative indexing
array=np.arange(1,31)
print(array)
array=array.reshape(5,6)
array

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [20]:
array[1][0]

np.int64(7)

In [21]:
array[0:2]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [22]:
array[0:2,0:3]

array([[1, 2, 3],
       [7, 8, 9]])

# operation

In [23]:
array1=np.arange(1,9).reshape(2,4)
array2=np.arange(11,19).reshape(2,4)
print(array1)
print(array2)

[[1 2 3 4]
 [5 6 7 8]]
[[11 12 13 14]
 [15 16 17 18]]


In [24]:
array1+array2

array([[12, 14, 16, 18],
       [20, 22, 24, 26]])

In [25]:
np.add(array1,array2)
#similar subtract , multiply , division
# a@b and a.dot(b) for matrix add and multiple

array([[12, 14, 16, 18],
       [20, 22, 24, 26]])

In [26]:
array1.max()
# similar for min

np.int64(8)

In [27]:
array1.argmax()
# gives index

np.int64(7)

In [28]:
# for sum
np.sum(array1)

np.int64(36)

In [29]:
# 1 for row and 0 for col
np.sum(array1,axis=1)

array([10, 26])

In [74]:
#concat in array
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [72]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [78]:
# split
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [79]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [84]:
#search
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

#sort
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

(array([3, 5, 6]),)
[[2 3 4]
 [0 1 5]]


In [88]:
# filters
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]

# y=arr%2==0
# print(y)
# newarr=arr[y]

print(newarr)

[False  True False  True]
[42 44]


In [95]:
# round floor ceil
arr = np.around(3.1666, 2)
print(arr)

arr = np.floor([-3.1666, 3.6667])
print(arr)

3.17
[-4.  3.]


# Random 

In [30]:
np.random.random(3)

array([0.10985459, 0.68986578, 0.22144015])

In [31]:
np.random.random((3,4))

array([[0.35222506, 0.24971998, 0.57451438, 0.78859788],
       [0.34332492, 0.76882957, 0.15450869, 0.29022497],
       [0.20127349, 0.25080462, 0.56410314, 0.8171837 ]])

In [32]:
np.random.randint(1,10)
# np.random.randint(1,10,(2,4))

8

# strings

In [33]:
a='hello how are you'
b='i am good'

In [34]:
np.char.add(a,b)

np.str_('hello how are youi am good')

In [35]:
np.char.upper(a)

array('HELLO HOW ARE YOU', dtype='<U17')

In [36]:
np.char.split(a)

array(list(['hello', 'how', 'are', 'you']), dtype=object)

In [37]:
np.char.replace(a,'a','b')

array('hello how bre you', dtype='<U17')